### ISSUE TITLE
Support view-only wallets

### ISSUE THREAD

**Issue by ppoliani** [ElrondNetwork/elrond-sdk#101]
I need to integrate the sdk into my existing system. More specifically I need to create a view-only HD wallet. That is to allow users submit the xpub and the derive all addresses in a deterministic manner. 

I have done similar things for other coins. More specifically in `bitcoinjs-lib` I could something like this

```
const rootKey = bip32.fromBase58(xpub)
rootKey.derivePath(path);
```

I'm struggling to accomplish something similar using this SDK. Could you please suggest if something like this is possible?

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.
