### ISSUE TITLE
Set a Gitpod environment

### ISSUE THREAD

**Issue by JulienMir** [ElrondNetwork/elrond-sdk#115]
Hi,

The project is amazing and I would really like to be a part of it by starting to build smart contracts for Elrond.
However, I'm using Windows and am not really willing to install a dual boot. VM offers bad UI for programming in my opinion.

I recently discovered Gitpod and I think it could really be a nice complement to the current tutorial.
It could have all the tools needed setup so you can quickly get your hands on what really matters.

I hope here is the right place to post about this issue.

Keep up the great work

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.

Furthermore, please have a look at: https://play.elrond.com
