### ISSUE TITLE
Ledger app repo is missing

### ISSUE THREAD

**Issue by hiddentao** [ElrondNetwork/elrond-sdk#117]
I clicked through to the repository for https://www.npmjs.com/package/@elrondnetwork/hw-app-elrond but it appears to be missing.

**Comment by tredondo** [comment]
Yet people blindly install it without source code to the tune of 7,000/week.

In the meantime, no response from devs, a year later.

![image](https://user-images.githubusercontent.com/10043369/143482440-0f9cb9ad-7a20-4675-8183-083ccb8442bd.png)

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.
