### ISSUE TITLE
Wallet Provider - problematic redirects

### ISSUE THREAD

**Issue by andreibancioiu** [ElrondNetwork/elrond-sdk#118]
Reported by @mihaieremia.

**Comment by mihaieremia** [comment]
Hi, 
The problem happens in this context.
Using the Wallet login provider I am redirected to the main Elrond wallet, but I am not redirected back to my dApp URL.
If I am opening a new tab with my dApp I am already authenticated as the session is already set somehow from the previous try.

**Comment by andreibancioiu** [comment]
Will be fixed by https://github.com/ElrondNetwork/elrond-sdk/pull/137.

**Comment by andreibancioiu** [comment]
Fixed in #153.

@mihaieremia, do you think you can confirm that it works as expected now?

Thank you!

**Comment by mihaieremia** [comment]
Sure I will give it a try :)

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.
