### ISSUE TITLE
JS-SDK compute Transaction Hash

### ISSUE THREAD

**Issue by zhjjj** [ElrondNetwork/elrond-sdk#123]
I tried to check the computation the transaction hash by JS-SDK.
https://github.com/ElrondNetwork/elrond-sdk/blob/19be3692ade540e4ec20ca887f8eabdefa9ec068/erdjs/src/transaction.ts#L303

The transaction is: https://explorer.elrond.com/transactions/8c761bc1ca5f4279951c0b4797f1896ed616b7503324af92280082d25216cf32
and my code is below:

    let provider = new ProxyProvider("https://api.elrond.com");
    await NetworkConfig.getDefault().sync(provider);

    let tx = new Transaction({
        gasPrice: new GasPrice(1000000000),
        gasLimit: new GasLimit(50000),
        receiver: new Address("erd1lanz397mngt637705m6sk67jjs9uuqp0rerce73ud48x3xvxtxjqe5umzj"),
        sender: new Address("erd1gpdzv5hclk90ykndhl5sucm3h4kksn23ehuvu69vjfcsqzgk3r5qps7c4p"),
        value: Balance.fromString('12900000000000000')
    });

    tx.setNonce(0);
    tx.applySignature(Signature.fromHex('7e8da1da57aff2ce985b5bebd4611867268cc86f6850e0d84974295b70b1b1d23c214440a039300c77f0d5a4cf8b8da40ee58fc1fcadd7a7a45a265df24db603'), tx.sender)
    console.log(tx.hash)

The result is 9c411414fa5a2d1b8e594de73869b45639054f3439788e4bc1184e1b2f724988, and the correct transaction hash is 8c761bc1ca5f4279951c0b4797f1896ed616b7503324af92280082d25216cf32.
Any problem in my code or  the transaction hash computation is not correct? 
Please help me fix this problem. Thanks!

**Comment by andreibancioiu** [comment]
Hi @zhjjj, should be fixed in #223.

Please let us know if the issue still persists.

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.
