### ISSUE TITLE
Please update Bouncy Castle

### ISSUE THREAD

**Issue by Neustradamus** [ElrondNetwork/elrond-sdk#124]
Please update Bouncy Castle
- https://www.bouncycastle.org/
- https://www.bouncycastle.org/releasenotes.html
- http://www.bouncycastle.org/latest_releases.html
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncy%20castle
- https://cve.mitre.org/cgi-bin/cvekey.cgi?keyword=bouncycastle
- https://www.cvedetails.com/vulnerability-list/vendor_id-7637/Bouncycastle.html

**Comment by bogdan-rosianu** [comment]
Hi!
Thank you for the notice!
We updated the library.

**Comment by Neustradamus** [comment]
@bogdan-rosianu, @andreibancioiu: Thanks!
If all projects were like you, the World will be better ^^

**Comment by Neustradamus** [comment]
@bogdan-rosianu, @andrei-diaconescu: Can you update to 1.69?
