### ISSUE TITLE
Creating a token from within a smart contract

### ISSUE THREAD

**Issue by JulienMir** [ElrondNetwork/elrond-sdk#143]
Hi,

I have the following process:

1. Payabale initializer where the creator sends at least 5eGLD to the contract. The token is not created yet as the contract's address is not defined.
2. A "mint" function that takes the name, the ticker and the initial supply as arguments and sends a transaction to the meta chain with constant options.
3. A "transfer" function that is meant to transfer to funds to the creator when the tokens have first been transfered to the contract.

I tried running this process on devnet and testnet but never managed to reach step 3:

- The SC 's balance is set in the init function but never updated after that.
- I use verification so that the "mint" function is not called twice, but they never seem to trigger (maybe indicating that it was not applied to the VM state).
- Step 2 is marked as successful on both networks, although no transactions exist between my SC and the ESDT SC.
- If i copy the data of the transaction and send it from my account, the token is created.

Also, I need to give the full token name to the "transfer" function (if step worked) but all I have is the human-readable name and the ticker.
It would be nice to have a sort of callback from the ESDT creator indicating that the token creation was successful and send back the full token name as well.

Thanks

**Comment by hiddentao** [comment]
I have also not yet been able to issue a token from within a smart contract. The transaction returns as successful, so I don't know what else is missing.

I also second the need to return the id of the token in the async call so that it can be referenced later on.

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.
