### ISSUE TITLE
Would you support a Dart sdk for Elrond ?

### ISSUE THREAD

**Issue by Kleak** [ElrondNetwork/elrond-sdk#174]
Hey teams,

I would like to start a SDK for [Dart](https://dart.dev) and by extension [Flutter](https://flutter.dev) since it become quite popular.
Would you support such initiative in some way ?

**Comment by Kleak** [comment]
I have started to organise what should be done [here](https://linear.app/kleak-dev/team/ESD/active)
You can also see what has been done.

Would be great if i could have a contact in the team in case I have a question regarding the SDK.

**Comment by andrei-marinica** [comment]
We had something similar recently, someone from the community created erdkotlin, check it out: https://github.com/ElrondNetwork/elrond-sdk/tree/master/erdkotlin

If you start coding and create a PR, we'll do our best to review it in time.

**Comment by Kleak** [comment]
Little update 🙂
I have moved the code [here](https://github.com/acolyte-xyz/elrond_sdk).

What I already support is :
- getting account from mnemonic
- sending transactions

Once I have more things (esdt, smart contract support) I will do a PR here.

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.
