### ISSUE TITLE
Installing erdpy on macOS Big Sur 11.2 fails

### ISSUE THREAD

**Issue by florinmatinca** [ElrondNetwork/elrond-sdk#194]
Hi guys,

I'm trying to install erdpy and I get the following output:

```
florinm@florinm-mbp ~ % python3 erdpy-up.py
INFO:installer:Checking user.
INFO:installer:Checking Python version.
INFO:installer:Python version: sys.version_info(major=3, minor=8, micro=2, releaselevel='final', serial=0)
INFO:installer:Checking operating system.
INFO:installer:Operating system: osx
INFO:installer:Removed previous installation (virtual environment).
INFO:installer:Packages found: <module 'ensurepip' from '/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/ensurepip/__init__.py'>, <module 'venv' from '/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/venv/__init__.py'>.
INFO:installer:Creating virtual environment in: /Users/florinm/elrondsdk/erdpy-venv.
CRITICAL:installer:Command '['/Users/florinm/elrondsdk/erdpy-venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']' died with <Signals.SIGABRT: 6>.
```

I also tried to setup the workspace from the VS Code Extension and I get the same output. I'm thinking maybe there is some configuration missing for my python environment, but I don't have any experience in that area.

**Comment by andreibancioiu** [comment]
Hello @florinmatinca, thanks for reporting the issue!

If you remove (or comment out) this line in the downloaded `erdpy-up.py` file, does the command `python3 erdpy-up.py` succeed afterwards?

```
https://github.com/ElrondNetwork/elrond-sdk/blob/master/erdpy-up.py#L159
```

**Comment by florinmatinca** [comment]
Hi @andreibancioiu, if I comment that line I get the same output.

**Comment by florinmatinca** [comment]
As expected, that was the problem. The original **erdpy-up.py** file works just fine, there is no need to comment that line because will cause a runtime error.

This [article](https://hackercodex.com/guide/python-development-environment-on-mac-osx/) helped me to correctly configure the python environment on Big Sur.
