### ISSUE TITLE
VSCode Setup Workspace error

### ISSUE THREAD

**Issue by florinmatinca** [ElrondNetwork/elrond-sdk#206]
Hi guys, I'm using VSCode Version: 1.53.2 and after successfully **erdpy** installation I also installed Elrond IDE extension.

However, when I run [Elrond: Setup Workspace] this is the output I get as an error:

<img width="549" alt="Screenshot 2021-02-21 at 22 51 53" src="https://user-images.githubusercontent.com/7703604/108638340-7c58a500-7497-11eb-9e2c-cd4d4ad920b9.png">

**Comment by florinmatinca** [comment]
I also removed VSCode completely and all local cache/previous installed extensions.

**Comment by florinmatinca** [comment]
Hi guys, any update on this ? I just checked on Ubuntu 20.4 with Python 3.6 and erdpy installed, latest VSCode and I get the same error when I try to setup workspace.

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.

Does the error persist? If so, please submit an issue here: https://github.com/ElrondNetwork/elrond-ide-vscode.
