### ISSUE TITLE
erdjs doesn't compile

### ISSUE THREAD

**Issue by claudiu-popovici** [ElrondNetwork/elrond-sdk#216]
I have added erdjs and erdtestjs with npm in a blank angular project and I am getting the following errors:

ERROR in node_modules/@elrondnetwork/erdjs/out/index.d.ts(10,10): error TS1005: 'from' expected.
node_modules/@elrondnetwork/erdjs/out/index.d.ts(10,13): error TS1005: ';' expected.
node_modules/@elrondnetwork/erdjs/out/index.d.ts(10,19): error TS1005: ';' expected.
node_modules/@elrondnetwork/erdjs/out/index.d.ts(10,24): error TS1005: ';' expected.

ERROR in node_modules/@elrondnetwork/erdjs/out/index.d.ts(10,10): error TS1141: String literal expected.
node_modules/@elrondnetwork/erdjs/out/index.d.ts(10,13): error TS2304: Cannot find name 'valid'.
node_modules/@elrondnetwork/erdjs/out/index.d.ts(10,19): error TS2304: Cannot find name 'from'.
node_modules/@elrondnetwork/erdjs/out/smartcontracts/argument.d.ts(34,30): error TS2304: Cannot find name 'BigInt'.
node_modules/@elrondnetwork/erdjs/out/smartcontracts/query.d.ts(41,15): error TS2304: Cannot find name 'BigInt'.
node_modules/@elrondnetwork/erdtestjs/out/world.d.ts(54,14): error TS2304: Cannot find name 'BigInt'.

**Comment by raduchiriac** [comment]
Can you give us more information about your `package.json`? From what I see so far `BigInt` has only been added after TypeScript 3.2. Maybe update your packages, install and re-run.

Do this:
`npx npm-check-updates -u && npm i`

**Comment by claudiu-popovici** [comment]
According to package.json, my ts version was 3.4.3. I have updated to 4.1.5 and seems to work fine new.
Thanks!
