### ISSUE TITLE
Feature: Sign transactions with PEM or JSON wallet

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-sdk#22]
As a follow-up to #21, a command to sign previously generated transactions is needed.

The sign operation must be available offline, so it can be performed on a different device than the one generating the tx.

As validation, the address of the wallet used should match the one embedded in the tx file.

**erdpy tx-sign tx-unsigned.json --pem PEM**

Another important feature is the ability to unlock and sign the transaction using a son wallet

**erdpy tx-sign tx-unsigned.json --wallet WALLET [--pass]**

**Comment by andreibancioiu** [comment]
@soringp, erdpy now has the commands `tx new` (without `--send`) to sign a transaction in offline mode, then the command `tx send` to dispatch it. Furthermore, one can now use `--keyfile` and `--passfile` flags.

Please leave a :+1: if everything is all right, so we can close this issue.
