### ISSUE TITLE
Feature: Create PEM file from secret phrase

### ISSUE THREAD

**Issue by soringp** [ElrondNetwork/elrond-sdk#23]
I'm not sure if this feature exists, but for the cold storage operations proposed for #21, the ability to produce a PEM file offline, from the 24 words seed is important.

**erdpy wallet recover --secret-phrase '24WORDS' --pem recovered.pem**

**[erdpy wallet recover --secret-phrase '24WORDS' --json recovered_wallet.json --pass PASS]**

An alternative to recovering directly to encrypted json wallet would be the option to encrypt a pem file and produce the json wallet.

Given the default derivation path, m/44'/508'/0'/0'/0', two optional params should be the _account_ and the _address_index_, allowing the recovery of multiple addresses:

**erdpy wallet recover --secret-phrase '24WORDS' --pem recovered_1_21.pem --account 1 --address-index 21**

This should recover the wallet for DP m/44'/508'/1'/0'/21'

**Comment by andreibancioiu** [comment]
Feature development is in progress. For the moment, one can create e PEM file using the mnemonic as follows:

```
erdpy wallet generate ./myaccount.pem --mnemonic="foo bar ..."
```

(the `generate` verb is a bit ambiguous indeed, it is subject to change)

**Comment by soringp** [comment]
Sounds great, thanks

**Comment by andreibancioiu** [comment]
[erdwalletjs-cli](https://github.com/ElrondNetwork/elrond-sdk/blob/master/erdwalletjs-cli/README.md) is a thin CLI wrapper over our [elrond-core-js](https://github.com/ElrondNetwork/elrond-core-js) library, which allows such wallet-specific operations.

**Comment by andreibancioiu** [comment]
@soringp please leave a :+1: if everything is all right and we can close this issue.
