### ISSUE TITLE
Add possibility to install a fixed toolchain to the rust module installer

### ISSUE THREAD

**Issue by rstancioiu** [ElrondNetwork/elrond-sdk#234]
### Issue ###
Based on the version of rust toolchain we can have smart contracts of different sizes.
As the deployment is based on the size of the wasm we can have different gas used values based on the rust version.
This is an issue in the case that several persons are collaborating on the same project, as we cannot control the version of rust that we are using. By default, today, as far as I understand we use the nightly version that takes the latest version from rust master.

Also today, as the tag is not taken into consideration at the rust installation, changing "dependencies.rust.tag" which is overridden when we are calling `erdpy deps` does not do anything.

### Solution ###
From the usage of tag, as far as I understood, it stands as the version of a module. Thus, if we continue in the same rhetoric, we could override the default toolchain by doing the following:
````
> erdpy deps install rust --overwrite --tag nightly-2018-08-01
````
Which would be the same as: calling
````
> rustup toolchain install nightly-2018-08-01
````
In case that no version is provided in the tag parameter, we can fall back to today's usage of taking the "nightly" version.

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.

The feature is now available in **erdpy**. If you experience any issues, please refer to https://github.com/ElrondNetwork/elrond-sdk-erdpy.
