### ISSUE TITLE
Feature: add magnitude to field "VALUE"

### ISSUE THREAD

**Issue by SupermonkyGroup** [ElrondNetwork/elrond-sdk#26]
It is inconvenient to indicate the amount of ERD to send in ERD^(-18)

e.g. in order to send 69 ERD it is necessary to put this in the value field:
erdpy --verbose tx-prepare-and-send --pem=PEM --value=690000000000000000  .....

In addition to applying the denomination for the VALUE field by default, perhaps you could add predefined operators for the orders of magnitude: atto (a) (10^-18), femto (f), pico (p), nano (n), 
  micro (u), milli (m), --1ERD-- kilo (K), mega (M), giga (G), tera (T), peta (P) and exa (E) (10^18)
So it could indicate:
1p instead of 0.000000000001
15m   -> 0.015 
1K      -> 1000 
1M     -> 1000000
20G    -> 20000000000
but I'm not sure if it would be valid to indicate something like this in that field:
--value=1K or --value=15m

PS. maybe with exa (E) prefix it could lead to confusion since it is the same letter as first of "ERD"
5E ERD -> 5x10^18 ERD not 5 ERD :)

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.
