### ISSUE TITLE
Erdjs: Add ability to sign messages

### ISSUE THREAD

**Issue by raress96** [ElrondNetwork/elrond-sdk#274]
Hello,
It would be really helpful if the erdjs library would add the ability to sign a message using Elrond Wallet on the frontend side (similar to how when using Web3 you can do this for example with MetaMask).
This would allow users to sign in to DApps using the wallet, and have user information stored on a 3rd party backend for example, that can be accessed if the signature is valid.
Not sure if this is feasible right now, but it would be a great addition IMO.
Thank you.

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.
