### ISSUE TITLE
[BUG] Wrong key in send_transactions of erdpy/proxy/core.py

### ISSUE THREAD

**Issue by anhnd** [ElrondNetwork/elrond-sdk#30]
I tried to send bunch of transactions and have to modify the file a little bit to make it works.
The old key: num_sent = response["numOfSentTxs"]
The new key(v1.0.132): num_sent = response["txsSent"]

**Comment by anhnd** [comment]
It's fixed with version 0.4.9 and 0.5.1

**Comment by andreibancioiu** [comment]
Thanks @anhnd for reporting - will close this now, as it has been fixed.
