### ISSUE TITLE
Error sending transaction: invalid hex sender address provided : invalid bech32 string length 0

### ISSUE THREAD

**Issue by mtalhasaleem502** [ElrondNetwork/elrond-sdk#318]
****
I am facing the " Error sending transaction: invalid hex sender address provided : invalid bech32 string length 0 " issue in the implementation of ElrondNetwork SDK even using the correct parameters of " Devnet"  Kindly resolve my issue please.

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.
