### ISSUE TITLE
erdpy - Cannot fetch transaction with null data

### ISSUE THREAD

**Issue by Kimus729** [ElrondNetwork/elrond-sdk#339]
$ erdpy account get-transactions --address {address} command fails when data is null for a transaction

Example : 

    {
        "hash": "7c6939319450058f9ebf69ee57b404ec0ae1c11e106d0f0b496df0fcd7de3e26",
        "fee": "50000000000000",
        "miniBlockHash": "28acbe7e26baad3256b57e7615f0b38b84ea1c6ce29f04467385d91196deb353",
        "nonce": 42,
        "round": 1312613,
        "value": "5000000000000000000",
        "receiver": "erd18cpz5dzlhnrz7s9uc9a73a4gtd5sq5a7te0snrasazfz80cqpsnsmg6tvs",
        "sender": "erd1yscr0krqszwurzh6jmtmh46zc3d3y7uucdftl8yxkt70r9jqlxpq096mn7",
        "receiverShard": 1,
        "senderShard": 2,
        "gasPrice": 1000000000,
        "gasLimit": 50000,
        "gasUsed": 50000,
        "data": null,
        "signature": "722a4bab722704e265cd2d7a68e6db4f0b7eb32a3762e14df489a40f3b674640d5384d32e62040bdf97b5543aee355ac5cafafbfa066542787015f33151d640d",
        "timestamp": 1631565678,
        "status": "success",
        "searchOrder": 1
    }

fails with 

Traceback (most recent call last):
  File "/home/usrdev02/elrondsdk/erdpy-venv/bin/erdpy", line 8, in <module>
    sys.exit(main())
  File "/home/usrdev02/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/cli.py", line 32, in main
    _do_main()
  File "/home/usrdev02/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/cli.py", line 58, in _do_main
    args.func(args)
  File "/home/usrdev02/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/cli_accounts.py", line 62, in get_account_transactions
    response = proxy.get_account_transactions(Address(address))
  File "/home/usrdev02/elrondsdk/erdpy-venv/lib/python3.9/site-packages/erdpy/proxy/core.py", line 46, in get_account_transactions
    data = (data[:TRUNCATE_DATA_THRESHOLD] + ' ... truncated ...') if len(data) > TRUNCATE_DATA_THRESHOLD else data
**TypeError: object of type 'NoneType' has no len()**

In  python3.9/site-packages/erdpy/proxy/core.py :

def get_account_transactions(self, address: Address):
        TRUNCATE_DATA_THRESHOLD = 75

        url = f"{self.url}/address/{address.bech32()}/transactions"
        response = do_get(url)
        transactions = response.get("transactions", [])
        for transaction in transactions:
            data = transaction.get("data", "")
            # default value not assigned using get method. When data = null then data is NoneType
            # data = "" if data is None else data
            data = (data[:TRUNCATE_DATA_THRESHOLD] + ' ... truncated ...') if len(data) > TRUNCATE_DATA_THRESHOLD else data
            transaction["data"] = data
        return transactions

**Comment by Kimus729** [comment]
$ erdpy config set proxy https://devnet-api.elrond.com
$ erdpy config dump
{
    "proxy": "https://devnet-api.elrond.com"
}

**Comment by filipac** [comment]
I just discovered the same error now when playing with devnet

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.

Do you still experience the issue? If so, please refer to https://github.com/ElrondNetwork/elrond-sdk-erdpy.
