### ISSUE TITLE
Depedency downloading using erdpy hangs indefinitely

### ISSUE THREAD

**Issue by willemolding** [ElrondNetwork/elrond-sdk#34]
The `erdpy contract test` command was silently hanging for me

OS: Ubuntu 20.04
Python 3.7.6

Using the --verbose flag gives the following:
```bash
erdpy --verbose contract test
INFO:projects.core:run_tests.project: /home/willem/repos/elrond/Crowdfunding
DEBUG:modules:install: name=arwentools, tag=g03d0b3f
INFO:downloader:download_url.url: https://ide.elrond.com/travis-builds/ARWEN_v0.3.20-24-ge8c5c68_linux_amd64.tar.gz
INFO:downloader:download_url.filename: /home/willem/ElrondSCTools/arwentools.g03d0b3f.tar.gz
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): ide.elrond.com:443
```

and it hangs there. Unsurprisingly `erdpy install arwentools` produces the same result. 

---

I was able to get around this issue by manually downloading the arwentools dependency from `https://ide.elrond.com/travis-builds/ARWEN_v0.3.20-24-ge8c5c68_linux_amd64.tar.gz` and extracting the contents to `~/ElrondSCTools/arwentools/g03d0b3f`

**Comment by willemolding** [comment]
Further investigation revealed this was an issue with my local urllib3 installation so closing the issue

**Comment by cdauphin39** [comment]
Can't install Arwentools with erdpy so I did what you said.  Once the elements have been copied, do you have to launch a command or do other actions?

![image](https://user-images.githubusercontent.com/63859903/153590418-470df5bb-0981-427c-aa9e-ed3f66553f4c.png)

**Comment by cdauphin39** [comment]
![image](https://user-images.githubusercontent.com/63859903/153590537-ce9c1af6-616c-4bba-b79a-7e1fa7f30fd2.png)
