### ISSUE TITLE
Missing export of TransactionWatcher in erdjs

### ISSUE THREAD

**Issue by ljcvok** [ElrondNetwork/elrond-sdk#340]
It seems that TransactionWatcher is not exported in erdjs/src/index.ts
There is a missing line 
`export * from "./transactionWatcher";`

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.

`transactionWatcher` has been exported: https://github.com/ElrondNetwork/elrond-sdk-erdjs/blob/main/src/index.ts#L11
