### ISSUE TITLE
proxy-playground/blocks http query example is not working

### ISSUE THREAD

**Issue by HarleyAppleChoi** [ElrondNetwork/elrond-sdk#345]
When I want to query both http functions at [proxy-playground/blocks](https://github.com/ElrondNetwork/elrond-sdk/blob/master/proxy-playground/blocks.http#L1)
They return 404:
{
  "statusCode": 404,
  "message": "Cannot GET /block/4294967295/34634",
  "error": "Not Found"
}

Please update the examples and tutorial to the latest version

**Comment by andreibancioiu** [comment]
Closing the issue before archiving the repository - please refer to the new repositories, instead.
