### ISSUE TITLE
Possible trimming issues of password file in erdpy

### ISSUE THREAD

**Issue by viastake** [ElrondNetwork/elrond-sdk#44]
After:
`erdwalletjs derive-key -m mnemonicfile -p passwordfile -k myrewardswallet.json`

A Keystore json file `myrewardswallet.json` is created with the right bech32 address.

We try to use the same `myrewardswallet.json` file with the same `passwordfile` in a staking transaction:

`erdpy --verbose validator stake --keyfile=myrewardswallet.json --value="2500000000000000000000" --number-of-nodes=1  --nodes-public-keys="$validatorblskey" --proxy=https://api.elrond.com --estimate-gas --recall-nonce --passfile=passwordfile`

Then `erdpy` gives the error:

`CRITICAL:cli:Provided keystore file password is invalid.`

The `myrewardswallet.json` Keystore file **does work** with the same password in the web wallet UI.

We already discussed this, assumably there are some issues with trimming newlines in the password file.

**Comment by andreibancioiu** [comment]
@viastake, this issue should not appear anymore with `erdpy 0.8.2`. Please leave a :+1: if everything is all right, so we can close this issue.

Thanks for reporting this!

**Comment by andreibancioiu** [comment]
Fixed some time ago, issue will be closed.
