### ISSUE TITLE
Compilation of Crowdfunding tutorial fails

### ISSUE THREAD

**Issue by alexandru-calinoiu** [ElrondNetwork/elrond-sdk#59]
Might be related to https://github.com/ElrondNetwork/elrond-sdk/issues/58

When trying to compile the project on step 3 I get the following error:

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/calin/Playground/elrond/CrowdFunding/wasm'
```

**Comment by andreibancioiu** [comment]
@alexandru-calinoiu, what is the current folder when running the command?

Furthermore, can you provide the output of the command `tree /home/calin/Playground/elrond/CrowdFunding`?

Side note - at this moment, the tutorial in the docs references the framework `elrond-wasm 0.5.3`, but erdpy isn't compatible with this version anymore (we have to update the tutorial). As a temporary workaround, you can create a dummy contract based on a template, using Elrond IDE, then edit the contract as desired.

**Comment by alexandru-calinoiu** [comment]
tree output

![image](https://user-images.githubusercontent.com/679198/94022644-fdfbb800-fdbd-11ea-95e7-3c4f7e0647f6.png)

Running from the base directory, this case `~/Playground/elrond/CrowdFunding`

**Comment by alexandru-calinoiu** [comment]
Will try the template and let you know if this works.

**Comment by andreibancioiu** [comment]
Fixed some time ago, will close this issue.
